std_msgs/Header header

bool DIRECTION_FWD = True
bool DIRECTION_REV = False

# For an explanation on the fields' meanings, see https://mjbogusz.gitlab.io/l6470-linux/
bool hi_z False
bool busy False
bool direction False
bool motor_stopped False
bool motor_accelerating False
bool motor_decelerating False
bool motor_const_speed False
bool undervoltage False
bool thermal_warning False
bool thermal_shutdown False
bool overcurrent False
bool step_loss_a False
bool step_loss_b False
